### ISSUE TITLE
No documentation for uzlib_uncompress_init()

### ISSUE THREAD

**Issue by madsci77** [pfalcon/uzlib#25]
There is no documentation provided for uzlib_uncompress_init(), and no explanation of the meaning and usage of the dict and dictLen parameters.

I've spent at least two hours attempting to integrate uzlib into an embedded project and as best I can tell, it's not going to work because of the dictionary buffer requirement.  No mention is made of how much dictionary buffer is required.  I've had to resort to reading articles on the details of the LZ77 algorithm and the GZIP file format to try to determine what's needed, and it seems that it always needs a 32 kB buffer.  If that's the case I'm not clear why the size is passed to the init function, when it always has to be the same.

Perhaps the library was written for people who already know the details of LZ7 and GZIP and don't need this information.  I was looking for a suitable decompressor for use in a deeply embedded system and this project claimed to be exactly that; turns out my definition of 'deeply embedded' is a little deeper than the author's - I've got about 12 kB of heap to work with.  That's not the author's fault, but to save anyone else from wasting time on the same mistake, perhaps  the readme could be updated to give a brief overview of the runtime memory requirements.

**Comment by pfalcon** [comment]
Thanks for your interest in uzlib. You're absolutely right that uzlib, just as thousands of other opensource projects, could use better documentation. I'm sure sponsors eager to remedy the situation are coming. In the meantime, please be prepared to study existing documentation, provided samples, usage examples in other projects, header files, source code, etc. And of course, to use a technology, you need to know it, so before start (or get productive) with uzlib, you definitely have read documentation for GZIP, DEFLATE, LZ, etc. algorithms and formats.
