### ISSUE TITLE
Decompression streaming support?

### ISSUE THREAD

**Issue by peacherwu** [pfalcon/uzlib#26]
Similar to [`#2`](https://github.com/pfalcon/uzlib/issues/2), I am looking for a way to stream compressed file for decompression.

I understand there's discussion as to how much the input buffer would be. I wonder how this relates to  `dict_size ` and `hash_bits` set at compression time?

**Comment by peacherwu** [comment]
I was able to implement a input stream buffer reading from decompressed file one byte at a time. Also I reduced the output buffer to 1K.   `comp.dict_size` is set to 1K also at compression time.

However, the `valgrind massif` program is still reporting a 15K memory usage. All Makefiles are the original. Is that normal?

**Comment by pfalcon** [comment]
Decompression streaming is supported, as clearly stated in the readme. Usage example can be found in included tgunzip.c. I'm not sure about other things, missing context/details.
