### ISSUE TITLE
Small files being skipped (while using ESP32-targz)

### ISSUE THREAD

**Issue by frankcohen** [pfalcon/uzlib#38]
Hi, thanks for publishing and maintaining uzlib. I am using the branch that appears in ESP32-targz, a tar decompression utility for ESP32 devices. A decompressed archive skips a text file containing JSON encoded data. It successfully decompresses audio (.m4a) and video (.mpg) binary files in the same archive.

I am creating the TAR archive on a Mac using:
COPYFILE_DISABLE=1 tar czf startup.tar.gz --exclude ".DS_Store" startup
Without these flags ESP32-targz skips all files after the .DS_Store and other files beginning with a period.

Perhaps this is not a uzlib issue, I thought I would check just in case.

Thanks! -Frank

**Comment by pfalcon** [comment]
Glad that you find the project useful!

But, the scope of this project is compression/decompression of zlib and gzip files, nothing beyond that (e.g., no tar). So, if you're able to provide a (small) .gz file which would decompress with uzlib to something else than the standard gzip decompresses it, I can look into it. Otherwise, I'd suggest to report issue to ESP32-targz first.

**Comment by frankcohen** [comment]
Thanks for the reply. I've been debugging ESP32-targz. I'm pretty sure the problem is in the way it handles tar extended data structures for multiple files. I haven't found it yet, still looking. Once I find and fix it I will be publishing my developer journal to Reddit. The combo of uzlib and untar is great! -Frank

**Comment by frankcohen** [comment]
I found the problem and posted a patch to the ESP32-targz library as [Issue #33](https://github.com/tobozo/ESP32-targz/issues/33). Also I posted to Reddit my developer journal of using ESP32-targz with uzlib as [Using TAR files in ESP32 with SD applications for easy multiple file transfers](https://www.reddit.com/r/arduino/comments/mjygkl/using_tar_files_in_esp32_with_sd_applications_for/)

**Comment by pfalcon** [comment]
Nice work! I assume this can be closed, feel free to reopen if an issue will be found on uzlib side.
