### ISSUE TITLE
Amalgamated source files

### ISSUE THREAD

**Issue by degaart** [pfalcon/uzlib#39]
Hello, I have a repo [other here](https://github.com/degaart/uzlib) which has modifications permitting generation of amalgamated sources (akin to sqlite3) if it interests you. It permits using uzlib by including only one header file and one source file into a project.

**Comment by pfalcon** [comment]
Thanks for dropping a line. I personally don't like "amalgamated sources" as IMHO they go against the spirit and nature of Open Source, as they're effectively means to obfuscate the sources, making it harder for people to study, modify, and contribute back the useful changes. Obviously, as anybody else in the industry, I deal with them at my (paid) job, but not in my own free time.
