### ISSUE TITLE
Minimum code size + memory space requirements?

### ISSUE THREAD

**Issue by sheffieldnikki** [pfalcon/uzlib#6]
Could you add a couple of lines of documentation with the actual minimum code size + memory space requirements for the library? Decompress-only and compress-only please?

I'd like to gzip compress XML transmitted by an embedded ESP8266. Even a low compression ratio would be fine if it means less time transmitting over WiFi, eating the battery life.

Thanks

**Comment by pfalcon** [comment]
To find that out, you would need to build it with *your* compiler, voila. But if you want to see numbers with *my* compiler, I added it to the README.
